#!/usr/bin/env bash
#
# Copyright 2018 org.LTR4L
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

jar=$(ls -1 ./target/scala-2.12/ltr4l*.jar|head -n 1)
echo $jar 

jars=$jar
for jar in $(ls ./lib/*jar) ; do
    jars=$jars:$jar
done

java -ea -cp $jars org.ltr4l.cli.Train $*
